language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules
    - public
    - .cache

before_install:
  - npm install -g gatsby-cli

install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: source
